# Full configuration reference available at:
# https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/reference.html
dh_auditor:
    timezone: 'GMT-3'
    enabled: true
    #User Provider necessário para o usuário estar no log de alteracao
    user_provider: 'dh_auditor.user_provider'
    security_provider: ~
    role_checker: ~
    providers:
        doctrine:
            viewer: true
            table_prefix: null
            table_suffix: '_audit'
