twig:
    file_name_pattern: '*.twig'
    globals:
        base_url: '%env(base_url)%'
        enviroment: '%env(enviroment)%'
        company: '%env(company)%'
        phrase: '%env(phrase)%'
        version: '%env(version)%'
        teamcreator: '%env(teamcreator)%'
        do_ping: '%env(do_ping)%'
        color: '%env(color)%'
        tiposequipamentos: [3,13]
        status_falha: '%env(status_falha)%'
        importacao: '%env(importacao)%'
        gestao_dados: '%env(gestao_dados)%'
        gestao_ip: '%env(gestao_ip)%'
        button_color: 'purple'
        
        invtek_theme: '%env(invtek_theme)%'

when@test:
    twig:
        strict_variables: true